//
//  StyleKit.swift
//  UtilityHelper
//
//  Created by Jacky Tay on 26/07/17.
//  Copyright (c) 2017 NZ Police. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class StyleKit : NSObject {

    //// Cache

    private struct Cache {
        static var imageOfReorder: UIImage?
        static var reorderTargets: [AnyObject]?
    }

    //// Drawing Methods

    public class func drawReorder() {

        //// Polygon Drawing
        let polygonPath = UIBezierPath()
        polygonPath.move(to: CGPoint(x: 12.5, y: 3))
        polygonPath.addLine(to: CGPoint(x: 17, y: 7))
        polygonPath.addLine(to: CGPoint(x: 8, y: 7))
        polygonPath.addLine(to: CGPoint(x: 12.5, y: 3))
        polygonPath.close()
        UIColor.gray.setFill()
        polygonPath.fill()


        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(rect: CGRect(x: 1, y: 12, width: 23, height: 1))
        UIColor.gray.setFill()
        rectanglePath.fill()


        //// Rectangle 2 Drawing
        let rectangle2Path = UIBezierPath(rect: CGRect(x: 1, y: 15, width: 23, height: 1))
        UIColor.gray.setFill()
        rectangle2Path.fill()


        //// Rectangle 3 Drawing
        let rectangle3Path = UIBezierPath(rect: CGRect(x: 1, y: 9, width: 23, height: 1))
        UIColor.gray.setFill()
        rectangle3Path.fill()


        //// Polygon 2 Drawing
        let polygon2Path = UIBezierPath()
        polygon2Path.move(to: CGPoint(x: 12.5, y: 22))
        polygon2Path.addLine(to: CGPoint(x: 8, y: 18))
        polygon2Path.addLine(to: CGPoint(x: 17, y: 18))
        polygon2Path.addLine(to: CGPoint(x: 12.5, y: 22))
        polygon2Path.close()
        UIColor.gray.setFill()
        polygon2Path.fill()
    }

    //// Generated Images

    public class var imageOfReorder: UIImage {
        if Cache.imageOfReorder != nil {
            return Cache.imageOfReorder!
        }

        UIGraphicsBeginImageContextWithOptions(CGSize(width: 25, height: 25), false, 0)
            StyleKit.drawReorder()

        Cache.imageOfReorder = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return Cache.imageOfReorder!
    }
}
